# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
# CONFIG_ZMK_DISPLAY=y

# PMW3610 Trackball
CONFIG_SPI=y
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=1000
